### ISSUE TITLE
[Epic] Add unit tests to project templates

### ISSUE THREAD

**Issue by justinvp** [pulumi/templates#865]
## Overview

Augment project templates with unit tests, using our existing APIs for unit testing.

### Basic

- [ ] typescript
- [ ] javascript
- [ ] python
- [ ] csharp
- [ ] go
- [ ] java

### AWS

- [ ] https://github.com/pulumi/templates/pull/863
- [ ] aws-javascript
- [ ] https://github.com/pulumi/templates/pull/864
- [ ] https://github.com/pulumi/templates/pull/867
- [ ] https://github.com/pulumi/templates/pull/866
- [ ] aws-java

### Azure

- [ ] azure-typescript
- [ ] azure-javascript
- [ ] azure-python
- [ ] azure-csharp
- [ ] azure-go
- [ ] azure-java

### Google Cloud

- [ ] gcp-typescript
- [ ] gcp-javascript
- [ ] gcp-python
- [ ] gcp-csharp
- [ ] gcp-go
- [ ] gcp-java

### Kubernetes

- [ ] kubernetes-typescript
- [ ] kubernetes-javascript
- [ ] kubernetes-python
- [ ] kubernetes-csharp
- [ ] kubernetes-go
- [ ] kubernetes-java
